In [63]:
import string
import pandas as pd
lowerCase = string.ascii_lowercase[:26]
upperCase = string.ascii_uppercase[:26]
arr = ['David','john','jack','john','adam','jack', 'adam', 'Ross', 'brent', 'Rachel']
array=[23,45,46,45,43,46,43,22,76,40]

eachChar = []
sortedChar = []
sortedArray = []
noDuplicates = []

def sort(sortedChar, arr):
    for i in range(len(sortedChar)):
        for j in range(len(arr)):
            if(sortedChar[i] == arr[j][0]):
                sortedArray.append(arr[j])
    return sortedArray

def removeDuplicates(sortedArray, noDuplicates):
    for i in sortedArray:
        if i not in noDuplicates:
            noDuplicates.append(i)
    return noDuplicates

def sortNames(arr):
    A = range(len(upperCase))
    for i in range(len(lowerCase)) or A: # a
        for j in range(len(arr)):
            eachChar.append(arr[j][0]) # [d,j,j,j,a,j]
            if((lowerCase[i] == eachChar[j]) or (upperCase[i] == eachChar[j])):
                sortedChar.append(eachChar[j]) # [a,d,j,j,j,j]

    #print(sortedChar)
    sort(sortedChar, arr)     
    removeDuplicates(sortedArray,noDuplicates)

    secondChar = []
    sortedSecondChar = []
    ascending = []

    for i in range(len(noDuplicates)):  # i = 0 noDup[0] = adam
        j = i+1 # j = 1, noDup[1] = David
        if (j == len(noDuplicates)):
            break
        if(noDuplicates[i][0] ==  noDuplicates[j][0]):
            secondChar.append(noDuplicates[i][1])
            secondChar.append(noDuplicates[j][1])
            for k in range(len(lowerCase)) or A:
                for l in range(len(secondChar)):
                    if((lowerCase[k] == secondChar[l]) or (upperCase[k] == secondChar[l])):
                        sortedSecondChar.append(secondChar[l])
            for m in sortedSecondChar:
                    if(noDuplicates[i][1] == m):
                        noDuplicates[j], noDuplicates[i] = noDuplicates[i], noDuplicates[j]

    #print(sortedSecondChar)
    return noDuplicates


noDuplicateNames = []
noDuplicateNames = sortNames(arr)
print(noDuplicateNames)
noDup = []
noDuplicateNumbers = []
noDuplicateNumbers = removeDuplicates(array, noDup)
print(noDuplicateNumbers)

#arr = ['David','john','jack','john','adam','jack', 'adam', 'Ross', 'brent', 'Rachel']
#array=[23,45,46,45,43,46,43,22,76,40]
dictionary = {}
for key in array:
    for value in arr:
        dictionary[key] = value
        arr.remove(value)
        break
print(dictionary)

noDuplicateNameDictionary = {}

for i in noDuplicateNames:
    for key in dictionary:
        if (i == dictionary[key]):
            for names in noDuplicateNames:
                names = key
                noDuplicateNameDictionary[names] = i
                
print(noDuplicateNameDictionary)

keys = []
value = [] 

for key in noDuplicateNameDictionary:
    keys.append(key)
    value.append(noDuplicateNameDictionary[key])

data = {'first column':value,
        'second column':keys}
 
df = pd.DataFrame(data)
df

['adam', 'brent', 'David', 'jack', 'john', 'Rachel', 'Ross']
[23, 45, 46, 43, 22, 76, 40]
{23: 'David', 45: 'john', 46: 'jack', 43: 'adam', 22: 'Ross', 76: 'brent', 40: 'Rachel'}
{43: 'adam', 76: 'brent', 23: 'David', 46: 'jack', 45: 'john', 40: 'Rachel', 22: 'Ross'}

  first column  second column
0         adam             43
1        brent             76
2        David             23
3         jack             46
4         john             45
5       Rachel             40
6         Ross             22

In [ ]:
()